spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      locator:
        enable: true
        lower-case-service-id: true
  #Api KeyCloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/mscursorealm
server:
  port: 8080


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka